<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <RootNamespace>TrainDatabase.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="8.3.0" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
        <PackageReference Include="System.Reactive" Version="6.0.2" />
    </ItemGroup>

</Project>
