// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainDatabase.Infrastructure.Database;

#nullable disable

namespace TrainDatabase.Infrastructure.Migrations
{
    [DbContext(typeof(TrainDbContext))]
    [Migration("20260614190604_MultiTractionJoinTable")]
    partial class MultiTractionJoinTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TrainDatabase.Infrastructure.Entities.VehicleCalibrationDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MeasuredSpeed")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeedStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "Direction", "SpeedStep")
                        .IsUnique();

                    b.ToTable("VehicleCalibrationData");
                });

            modelBuilder.Entity("TrainDatabase.Infrastructure.Entities.VehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Dummy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InvertTraction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Railway")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegulationStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TractionBackward")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TractionForward")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TrainDatabase.Infrastructure.Entities.VehicleFunctionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ButtonType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnumType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowFunctionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("TrainDatabase.Infrastructure.Entities.VehicleTractionEntity", b =>
                {
                    b.Property<int>("LeadVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberVehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeadVehicleId", "MemberVehicleId");

                    b.HasIndex("MemberVehicleId");

                    b.ToTable("VehicleTractions");
                });

            modelBuilder.Entity("TrainDatabase.Infrastructure.Entities.VehicleCalibrationDataEntity", b =>
                {
                    b.HasOne("TrainDatabase.Infrastructure.Entities.VehicleEntity", "Vehicle")
                        .WithMany("VehicleCalibrations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TrainDatabase.Infrastructure.Entities.VehicleFunctionEntity", b =>
                {
                    b.HasOne("TrainDatabase.Infrastructure.Entities.VehicleEntity", "Vehicle")
                        .WithMany("Functions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TrainDatabase.Infrastructure.Entities.VehicleTractionEntity", b =>
                {
                    b.HasOne("TrainDatabase.Infrastructure.Entities.VehicleEntity", "Lead")
                        .WithMany("TractionMembers")
                        .HasForeignKey("LeadVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainDatabase.Infrastructure.Entities.VehicleEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("TrainDatabase.Infrastructure.Entities.VehicleEntity", b =>
                {
                    b.Navigation("Functions");

                    b.Navigation("TractionMembers");

                    b.Navigation("VehicleCalibrations");
                });
#pragma warning restore 612, 618
        }
    }
}
