<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <RootNamespace>TrainDatabase.UI.Desktop</RootNamespace>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TrainDatabase.UI\TrainDatabase.UI.csproj" />
        <ProjectReference Include="..\TrainDatabase.Composition\TrainDatabase.Composition.csproj" />
    </ItemGroup>

</Project>
